# Generated by Django 5.0.9 on 2024-11-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('subscriptions', '0002_alter_subscriptions_options_subscriptions_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptions',
            options={'permissions': [('advanced', 'Advanced perm'), ('pro', 'Pro perm'), ('basic', 'Basic perm'), ('basic_ai', 'Basic AI perm')], 'verbose_name': 'Subscription', 'verbose_name_plural': 'Subscriptions'},
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='permissions',
            field=models.ManyToManyField(to='auth.permission'),
        ),
    ]
