# Generated by Django 5.0.9 on 2024-11-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0014_subscriptions_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='subtitle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
