# Generated by Django 5.0.9 on 2024-11-25 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagevisits',
            options={'verbose_name': 'Page Visit', 'verbose_name_plural': 'Page Visits'},
        ),
    ]
